name: CI/CD for Flask App

on:
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Terraform plan & apply for EKS Cluster
  eks_setup:
    name: Terraform EKS Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.2

      - name: Initialize Terraform
        working-directory: terraform/src
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/src
        run: terraform plan -out=tfplan

      - name: Terraform Apply (if necessary)
        working-directory: terraform/src
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Step 2: Build Docker image and push to ECR
  docker_build:
    name: Build and Push Docker Image to ECR
    needs: eks_setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust according to your region

      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Set build tag
        id: vars
        run: echo "BUILD_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build Docker image with build tag
        run: docker build -t flask-app:${{ env.BUILD_TAG }} ./docker

      - name: Tag Docker image with build tag
        run: docker tag flask-app:${{ env.BUILD_TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/flask-app:${{ env.BUILD_TAG }}

      - name: Push Docker image to ECR with build tag
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/flask-app:${{ env.BUILD_TAG }}

  # Step 3: Update Helm chart and deploy to EKS
  deploy_to_eks:
    name: Deploy to EKS
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Helm chart values.yaml with new image tag
        run: |
          sed -i "s|image:.*|image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/flask-app:${{ env.BUILD_TAG }}|g" flask-app-chart/values.yaml

      - name: Set up kubectl
        uses: aws-actions/eks-kubectl-action@v1
        with:
          cluster-name: "my-cluster"
          region: "us-east-1"
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/EKS-Admin-Role

      - name: Deploy using Helm
        run: |
          helm upgrade --install flask-app ./flask-app-chart --namespace default
